### ISSUE TITLE
Does the standard define 'data' as a JSON object?

### ISSUE THREAD

**Issue by mz8i** [omniti-labs/jsend#1]
One thing that is not immediately clear from the specification is whether the 'data' key of the response should always be either a JSON object or a null, or whether it can be any valid JSON value. Indeed, the examples only show these two options, but other possibilities are not explicitly ruled out.
An example of a different format:
```
{
    "status": "success",
    "data": "Some string value"
}
```
If an endpoint specifically returns a single value of a primitive type, I am wondering if packaging that in an additional JSON object would be a bit superfluous?

**Comment by brenc** [comment]
Reading through the spec carefully, it says `data` is either a wrapper for other data or `null`. Personally, I've decided to stick to the spec as written. For example:
```javascript
return {
  status: 'fail',
  data: {
    message
  }
}
```

**Comment by xzilla** [comment]
I generally recommend using data be a json object, but ISTR we've had some corner cases where we needed to be "creative", so we left some room there just in case.
