### ISSUE TITLE
HTTP status codes

### ISSUE THREAD

**Issue by Baterka** [omniti-labs/jsend#3]
We are discussing some changes to specification here: https://github.com/Prestaul/jsend/issues/11
I think, specification need to be updated to define HTTP statuses too.

**Comment by trondhuso** [comment]
Maybe you should ask for some contribution from this guy:
https://medium.com/@bojanmajed/standard-json-api-response-format-c6c1aabcaa6d

**Comment by xzilla** [comment]
Noted.
