### ISSUE TITLE
important

### ISSUE THREAD

**Issue by bitbabit** [omniti-labs/jsend#7]
https://www.quora.com/What-are-the-things-which-are-banned-in-other-countries-except-in-India

Media will never inform you??
Nestle company accepts that they add juice extracted from Beef in chocolate Kitkat.
______________________
Media never informed you ???
That in a case in Chennai high court Fair & Lovely company accepted that the cream contains the oil from Pig fats !!
______________________
media never informed us that Vicks is banned in how many countries of Europe ! There it has been declared as slow poison ! But in our country we see it's advertising on TV whole day !!
_____________________
media never informed us that Life bouy is neither bath soap nor toilet soap ! But it's
a Cabolic soap used for bathing animals !
Europe uses Life bouy for Dogs ! And in our country millions of humans use it !!
______________________
media never informed us ! ???????????
That Coke, Pepsi is in reality toilet cleaner ! it has been proved that it contains 21 types of different poisons ! And it's sale is banned in the canteen of indian parliament ! But it is sold in whole country !!
____________________
media never informed us ????
That foreign companies selling health tonics like Boost
Complan
Horlics
Maltova
Protin-ex., were tested in Delhi at All India Institute (which houses biggest laboratory in india) and it was found that it is made from the waste left after oil is extracted from Groundnut ! Which is food for animals ! From this waste they make health tonic !!
______________________
media never informed us ??????
When Amitabh Bachhan was operated in hospital for 10 long hours !
Doctor had to cut and remove large intestine !! and doctor had told him that it has rotten due to drinking of soft drinks like Coke, Pepsi ! And then he stopped advertising coke
pepsi !
______________________
Media is faithful to the advertisers.

Lots of people enjoy Pizzas today.
Let's have a look over pizza companies
"Pizza Hut
Dominos
KFC
McDonalds
Pizza Corner
Papa John’s Pizza
California Pizza Kitchen
Sal’s Pizza"
These are all american companies,
Note:- to make Pizza tasty...
E-631 flavor Enhancer is added which is made from Pork or Pig meat.
● Attention friends if following codes are mentioned on food packs then you should know what you are unknowingly consuming.
E 322 - Beef
E 422 - Alcohol
E 442 - Alcohol & Chemical
E 471 - Beef & Alcohol
E 476 - Alcohol
E 481 - mixture of Beef and Pork
E 627 - Dangerous Chemical
E 472 - mixture of Beef, meat & Pork
E 631 - Oil extracted from Pig fats.
● Note - you will find these codes mostly in products of foreign companies like :- Chips , Biscuits , Chewing Gums, Toffees, Kurkure and Maggi !
● Don't ignore pay your kind attention atleast for the well being of your kids, if in doubt then search by yourself through your sources if not internet. (Google)
● Look at ingredient on Maggi pack, you will find flavor (E-635 ).
● Also look for following codes on Google :-
E100, E110, E120, E140, E141, E153, E210, E213, E214, E216, E234, E252, E270, E280, E325, E326, E327, E334, E335, E336, E337, E422, E430, E431, E432, E433, E434, E435, E436, E440, E470, E471, E472, E473, E474, E475, E476, E477, E478, E481, E482, E483, E491, E492, E493, E494, E495, E542, E570, E572, E631, E635, E904.

**Comment by xzilla** [comment]
yay spam
