### ISSUE TITLE
Can I use the icon of JSend in any package in any language?

### ISSUE THREAD

**Issue by zmjack** [omniti-labs/jsend#8]
JSend is a great standard.

Can I use the icon of JSend in any package in any language?

The website of JSend seems to be closed.
I can't find the icon anymore...

**Comment by xzilla** [comment]
Sorry... not sure what icon, or even what site, you're referring to.

**Comment by zmjack** [comment]
I remember that an icon is used on your old website, looks like a **beaker flask**, **black and white picture**.

But the website can not open again, i can't find the icon.

The old website is
    **http://labs.omniti.com/labs/jsend**
Now, it's redirected here.
